name: Ship job results

description: This workflow is responsible for shipping the job results to ElasticSearch

inputs:
  release_tag:
    description: "The unique release tag"
    type: string
    required: true
  helm_env:
    description: "Helm Chart Environment"
    type: string
    required: true
  elastic_host:
    description: "ElasticSearch Host URL"
    type: string
    required: true
  elastic_key:
    description: "ElasticSearch API Key"
    type: string
    required: true
  elastic_index:
    description: "ElasticSearch Index Name"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Ship job results
      uses: actions/github-script@v7
      with:
        script: |
          async function main() {
                   const runId = context.runId;
                   const { data } = await github.rest.actions.listJobsForWorkflowRun({
                       owner: context.repo.owner,
                       repo: context.repo.repo,
                       run_id: runId
                   });

                   // Exclude skipped and notify job logs
                   const jobs = data.jobs.filter(job => (!!job.conclusion && job.conclusion !== 'skipped') 
                           && !job.name?.toLowerCase().includes('notify'));
                   for (const job of jobs) {
                       const body = {
                           "@timestamp": job.completed_at,
                           job_name: job.name,
                           workflow: context.workflow,
                           status: job.status,
                           conclusion: job.conclusion,
                           started_at: job.started_at,
                           completed_at: job.completed_at,
                           owner: context.repo.owner,
                           repo: context.repo.repo,
                           run_id: context.runId,
                           release_id: process.env.RELEASE_TAG,
                           env: process.env.HELM_ENV,
                           actor: process.env.ACTOR,
                           origin: "github"
                       }
                       console.log(process.env.ELASTIC_HOST.substring(6, process.env.ELASTIC_HOST.length));
                       console.log(process.env.ELASTIC_KEY.substring(6, process.env.ELASTIC_KEY.length));
                       const elasticUrl = `${process.env.ELASTIC_HOST}/${process.env.ELASTIC_INDEX}/_doc`;
                       console.log(`Posting to URL = ${elasticUrl}`);
                       console.log(`Posting job ${job.name} to Elastic`);
                       console.log("Request : " + JSON.stringify(body));
                       const response = await fetch(elasticUrl, {
                           method: 'POST',
                           headers: {
                           'Content-Type': 'application/json',
                           'Authorization': `ApiKey ${process.env.ELASTIC_KEY}`
                           },
                           body: JSON.stringify(body)
                       });

                       const data = await response.json();
                       console.log("Response : " + JSON.stringify(data));
                       console.log(`Indexed job ${job.name}`);
                   }
               }
               main().catch(err => {
                   core.setFailed(err.message);
               });
        env:
        ELASTIC_HOST: ${{ inputs.elastic_host }}
        ELASTIC_KEY: ${{ inputs.elastic_key }}
        ELASTIC_INDEX: ${{ inputs.elastic_index }}
        HELM_ENV: ${{ inputs.helm_env }}
        ACTOR: ${{ github.actor }}
