name: Ship job results

description: This workflow is responsible for shipping the job results to ElasticSearch

inputs:
  release_tag:
    description: "The unique release tag"
    type: string
    required: true
  helm_env:
    description: "Helm Chart Environment"
    type: string
    required: true
  elastic_host:
    description: "ElasticSearch Host URL"
    type: string
    required: true
  elastic_key:
    description: "ElasticSearch API Key"
    type: string
    required: true
  elastic_index:
    description: "ElasticSearch Index Name"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Ship job results
      env:
        ELASTIC_HOST: ${{ inputs.elastic_host }}
        ELASTIC_KEY: ${{ inputs.elastic_key }}
        ELASTIC_INDEX: ${{ inputs.elastic_index }}
        HELM_ENV: ${{ inputs.helm_env }}
        RELEASE_TAG: ${{ inputs.release_tag }}
        ACTOR: ${{ github.actor }}
      uses: actions/github-script@v7
      with:
        script: |
          const script = require('${{ github.action_path }}/../../scripts/ship-logs-to-elastic.cjs');
          await script({ github, context, core })
